title: Kamikaze Kapanadze
description: A website with a blog
footer_text: Copyright 2021 Anna Kapanadze
header_feature_image: ../uploads/photo-1583133269464-b721db5345f4.webp
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
