title: Upscale Type
description: ""
footer_text: Copyright 2021 Anna Kapanadze
header_feature_image: ../uploads/photo-1414235077428-338989a2e8c0.webp
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: ../uploads/logoo.png
favicon: ../uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
