title: Upscale Type
description: ""
footer_text: Copyright 2021 Anna Kapanadze
header_feature_image: ""
header_text: ""
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: ""
gridlayout: false
fixednavbar: false
upzoom: true
