title: Itchy Knee
description: A website with a blog
footer_text: Copyright 2021 Anna Kapanadze
header_feature_image: ../uploads/miri-mina-9y6ztxxp9wc-unsplash.jpg
header_text: My Dream Blog
header_text_color: "#ffffff"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
